apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
spec:
  project: default
  source:
    repoURL: 'http://gitlab.local/cicd/deployment-manifests.git'
    path: apps/postgres
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
