replicaCount: 1

image:
  repository: 10.6.18.24:8080/bpm-connector/bpm-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: bpm.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
